import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';
import { Loader2, CheckCircle2, Package, DollarSign, CreditCard, ArrowLeft, Building2, Copy } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

// SPEI account details
const SPEI_ACCOUNT = {
  bank: 'BBVA México',
  clabe: '012180001234567890',
  accountNumber: '0123456789',
  beneficiary: 'Mercado Industrial SA de CV',
  rfc: 'MIN210101ABC',
};

const CheckoutContraoferta = () => {
  const { offerId } = useParams<{ offerId: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [isProcessing, setIsProcessing] = useState(false);
  const [paymentMethod, setPaymentMethod] = useState<'mercadopago' | 'spei'>('spei');
  const [showPaymentStep, setShowPaymentStep] = useState(false);
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [createdOrder, setCreatedOrder] = useState<any>(null);
  const [speiReference, setSpeiReference] = useState('');

  const { data: offer, isLoading: offerLoading } = useQuery({
    queryKey: ['counter-offer', offerId],
    queryFn: async () => {
      if (!offerId) return null;
      const { data, error } = await supabase
        .from('offers')
        .select('*')
        .eq('id', offerId)
        .single();
      
      if (error) throw error;
      return data;
    },
    enabled: !!offerId,
  });

  const { data: product, isLoading: productLoading } = useQuery({
    queryKey: ['product-for-offer', offer?.product_id],
    queryFn: async () => {
      if (!offer?.product_id) return null;
      const { data, error } = await supabase
        .from('products')
        .select('*')
        .eq('id', offer.product_id)
        .single();
      
      if (error) throw error;
      return data;
    },
    enabled: !!offer?.product_id,
  });

  // Verify user owns this offer
  useEffect(() => {
    if (offer && user && offer.user_id !== user.id) {
      toast.error('No tienes acceso a esta oferta');
      navigate('/');
    }
  }, [offer, user, navigate]);

  const counterOfferPrice = (offer as any)?.counter_offer_price;
  const finalPrice = counterOfferPrice || offer?.offer_price;
  const isCounterOffer = offer?.status === 'counter_offer';

  const copyToClipboard = (text: string, field: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(field);
    toast.success('Copiado al portapapeles');
    setTimeout(() => setCopiedField(null), 2000);
  };

  const handleProceedToPayment = async () => {
    if (!offer || !finalPrice || !product) {
      toast.error('Error: Datos incompletos');
      return;
    }

    setIsProcessing(true);
    try {
      // Create order — order_number is generated by DB trigger set_order_number
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          user_id: user?.id,
          customer_name: offer.customer_name,
          customer_email: offer.customer_email,
          customer_phone: offer.customer_phone,
          shipping_address: 'Por definir',
          subtotal: finalPrice,
          total: finalPrice,
          status: 'pending',
          order_type: 'purchase',
          notes: isCounterOffer 
            ? `Contraoferta aceptada - Oferta original: $${offer.offer_price}` 
            : `Oferta aceptada: $${offer.offer_price}`,
        } as any)
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order item
      await supabase
        .from('order_items')
        .insert({
          order_id: order.id,
          product_id: product.id,
          product_sku: product.sku,
          product_title: product.title,
          product_image: product.images?.[0],
          unit_price: finalPrice,
          quantity: 1,
          total_price: finalPrice,
        });

      // Update offer status to 'accepted' — will be set to 'paid' after payment confirmed
      await supabase
        .from('offers')
        .update({ status: 'accepted' })
        .eq('id', offerId);

      setCreatedOrder(order);
      setShowPaymentStep(true);
      toast.success('Pedido creado. Selecciona tu método de pago.');
    } catch (error) {
      console.error('Error creating order:', error);
      toast.error('Error al crear el pedido');
    } finally {
      setIsProcessing(false);
    }
  };

  const handleMercadoPagoPayment = async () => {
    if (!createdOrder || !product) return;

    setIsProcessing(true);
    try {
      const { data, error } = await supabase.functions.invoke('mercadopago-create-preference', {
        body: {
          items: [{
            id: product.id,
            title: product.title,
            unit_price: finalPrice,
            quantity: 1,
          }],
          orderId: createdOrder.id,
          payer: {
            name: offer?.customer_name,
            email: offer?.customer_email,
          },
        },
      });

      if (error) throw error;

      if (data?.init_point) {
        window.location.href = data.init_point;
      } else {
        throw new Error('No se recibió URL de pago');
      }
    } catch (error) {
      console.error('Error with MercadoPago:', error);
      toast.error('Error al procesar pago con MercadoPago');
    } finally {
      setIsProcessing(false);
    }
  };

  const handleConfirmSPEI = async () => {
    if (!createdOrder) return;
    try {
      const baseNotes = isCounterOffer
        ? `Contraoferta aceptada - Oferta original: $${offer?.offer_price}`
        : `Oferta aceptada: $${offer?.offer_price}`;
      await supabase
        .from('orders')
        .update({
          status: 'processing',
          notes: speiReference.trim()
            ? `${baseNotes} | Referencia SPEI: ${speiReference.trim()}`
            : baseNotes,
        })
        .eq('id', createdOrder.id);
      // Mark offer as paid now that SPEI transfer was declared
      await supabase
        .from('offers')
        .update({ status: 'paid' })
        .eq('id', offerId);
    } catch (err) {
      console.error('Error updating order status:', err);
    }
    toast.success('¡Gracias! Procesaremos tu pedido al confirmar la transferencia.');
    navigate(`/checkout/success?order=${createdOrder.order_number}`);
  };

  if (offerLoading || productLoading) {
    return (
      <div className="min-h-screen bg-background">
        <Header />
        <main className="container mx-auto px-4 py-12">
          <div className="flex items-center justify-center py-20">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
          </div>
        </main>
        <Footer />
      </div>
    );
  }

  if (!offer || (offer.status !== 'counter_offer' && offer.status !== 'accepted')) {
    return (
      <div className="min-h-screen bg-background">
        <Header />
        <main className="container mx-auto px-4 py-12">
          <div className="max-w-lg mx-auto text-center py-20">
            <h1 className="text-2xl font-bold mb-4">Oferta no disponible</h1>
            <p className="text-muted-foreground mb-6">
              Esta oferta ya no está disponible o ha sido procesada.
            </p>
            <Button onClick={() => navigate('/')}>
              <ArrowLeft className="mr-2" size={16} />
              Volver al inicio
            </Button>
          </div>
        </main>
        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 py-12">
        <div className="max-w-2xl mx-auto">
          <Button 
            variant="ghost" 
            onClick={() => navigate(-1)}
            className="mb-6"
          >
            <ArrowLeft className="mr-2" size={16} />
            Volver
          </Button>

          {!showPaymentStep ? (
            // Step 1: Offer Summary
            <Card className="overflow-hidden">
              <CardHeader className={`bg-gradient-to-r ${isCounterOffer ? 'from-blue-500 to-blue-600' : 'from-green-500 to-green-600'} text-white`}>
                <CardTitle className="flex items-center gap-2">
                  <DollarSign size={24} />
                  {isCounterOffer ? 'Contraoferta Recibida' : '¡Oferta Aceptada!'}
                </CardTitle>
                <CardDescription className="text-white/80">
                  {isCounterOffer 
                    ? 'El vendedor ha respondido con una contraoferta' 
                    : 'El vendedor ha aceptado tu oferta. ¡Procede al pago!'}
                </CardDescription>
              </CardHeader>
              <CardContent className="p-6 space-y-6">
                {/* Product Info */}
                {product && (
                  <div className="flex items-center gap-4 p-4 bg-muted/50 rounded-lg">
                    <img
                      src={product.images?.[0] || '/placeholder.svg'}
                      alt={product.title}
                      className="w-20 h-20 rounded-lg object-cover"
                    />
                    <div className="flex-1">
                      <div className="flex items-center gap-2 text-sm text-muted-foreground mb-1">
                        <Package size={14} />
                        Producto
                      </div>
                      <h3 className="font-semibold">{product.title}</h3>
                      <p className="text-sm text-muted-foreground">SKU: {product.sku}</p>
                    </div>
                  </div>
                )}

                {/* Price Display */}
                {isCounterOffer ? (
                  <div className="grid grid-cols-2 gap-4">
                    <div className="p-4 border border-border rounded-lg">
                      <p className="text-sm text-muted-foreground mb-1">Tu oferta</p>
                      <p className="text-xl font-semibold line-through text-muted-foreground">
                        ${offer.offer_price.toLocaleString('es-MX', { minimumFractionDigits: 2 })}
                      </p>
                    </div>
                    <div className="p-4 border-2 border-blue-500 rounded-lg bg-blue-50 dark:bg-blue-950">
                      <p className="text-sm text-blue-600 font-medium mb-1">Contraoferta</p>
                      <p className="text-2xl font-bold text-blue-600">
                        ${counterOfferPrice?.toLocaleString('es-MX', { minimumFractionDigits: 2 })}
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="p-4 border-2 border-green-500 rounded-lg bg-green-50 dark:bg-green-950">
                    <p className="text-sm text-green-600 font-medium mb-1">Precio acordado</p>
                    <p className="text-2xl font-bold text-green-600">
                      ${finalPrice?.toLocaleString('es-MX', { minimumFractionDigits: 2 })}
                    </p>
                  </div>
                )}

                {/* Admin Notes */}
                {offer.admin_notes && (
                  <div className="p-4 bg-muted/50 rounded-lg">
                    <p className="text-sm font-medium mb-1">Mensaje del vendedor:</p>
                    <p className="text-muted-foreground">{offer.admin_notes}</p>
                  </div>
                )}

                {/* Action Button */}
                <Button 
                  onClick={handleProceedToPayment}
                  disabled={isProcessing}
                  className={`w-full font-bold py-6 text-lg ${isCounterOffer ? 'bg-blue-600 hover:bg-blue-700' : 'bg-green-600 hover:bg-green-700'} text-white`}
                >
                  {isProcessing ? (
                    <Loader2 className="animate-spin mr-2" size={20} />
                  ) : (
                    <CreditCard className="mr-2" size={20} />
                  )}
                  {isCounterOffer ? 'Aceptar y Pagar' : 'Proceder al Pago'} ${finalPrice?.toLocaleString('es-MX')}
                </Button>

                {/* Trust Indicators */}
                <div className="flex items-center justify-center gap-6 pt-4 border-t border-border">
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <CheckCircle2 size={16} className="text-green-500" />
                    Pago seguro
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <CheckCircle2 size={16} className="text-green-500" />
                    Garantía de compra
                  </div>
                </div>
              </CardContent>
            </Card>
          ) : (
            // Step 2: Payment Method Selection
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <CreditCard size={24} />
                  Selecciona tu método de pago
                </CardTitle>
                <CardDescription>
                  Pedido #{createdOrder?.order_number} - Total: ${finalPrice?.toLocaleString('es-MX', { minimumFractionDigits: 2 })}
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <RadioGroup
                  value={paymentMethod}
                  onValueChange={(value) => setPaymentMethod(value as 'mercadopago' | 'spei')}
                  className="space-y-4"
                >
                  <div className={`flex items-center space-x-4 p-4 rounded-lg border-2 transition-all cursor-pointer ${paymentMethod === 'spei' ? 'border-primary bg-primary/5' : 'border-border'}`}>
                    <RadioGroupItem value="spei" id="spei" />
                    <Label htmlFor="spei" className="flex items-center gap-3 cursor-pointer flex-1">
                      <Building2 className="h-6 w-6" />
                      <div>
                        <p className="font-medium">Transferencia SPEI</p>
                        <p className="text-sm text-muted-foreground">Transfiere desde tu banco</p>
                      </div>
                    </Label>
                  </div>

                  <div className={`flex items-center space-x-4 p-4 rounded-lg border-2 transition-all cursor-pointer ${paymentMethod === 'mercadopago' ? 'border-primary bg-primary/5' : 'border-border'}`}>
                    <RadioGroupItem value="mercadopago" id="mercadopago" />
                    <Label htmlFor="mercadopago" className="flex items-center gap-3 cursor-pointer flex-1">
                      <CreditCard className="h-6 w-6" />
                      <div>
                        <p className="font-medium">MercadoPago</p>
                        <p className="text-sm text-muted-foreground">Tarjeta, débito u otros métodos</p>
                      </div>
                    </Label>
                  </div>
                </RadioGroup>

                {/* SPEI Details */}
                {paymentMethod === 'spei' && (
                  <div className="p-4 bg-muted/50 rounded-lg space-y-4">
                    <h4 className="font-semibold flex items-center gap-2">
                      <Building2 size={18} />
                      Datos para transferencia
                    </h4>
                    
                    {[
                      { label: 'Banco', value: SPEI_ACCOUNT.bank, key: 'bank' },
                      { label: 'CLABE', value: SPEI_ACCOUNT.clabe, key: 'clabe' },
                      { label: 'Cuenta', value: SPEI_ACCOUNT.accountNumber, key: 'account' },
                      { label: 'Beneficiario', value: SPEI_ACCOUNT.beneficiary, key: 'beneficiary' },
                      { label: 'Monto', value: `$${finalPrice?.toLocaleString('es-MX', { minimumFractionDigits: 2 })} MXN`, key: 'amount' },
                      { label: 'Referencia', value: createdOrder?.order_number || '', key: 'reference' },
                    ].map((item) => (
                      <div key={item.key} className="flex justify-between items-center py-2 border-b border-border last:border-0">
                        <span className="text-sm text-muted-foreground">{item.label}</span>
                        <div className="flex items-center gap-2">
                          <span className="font-mono font-medium">{item.value}</span>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8"
                            onClick={() => copyToClipboard(item.value, item.key)}
                          >
                            {copiedField === item.key ? (
                              <CheckCircle2 className="h-4 w-4 text-green-500" />
                            ) : (
                              <Copy className="h-4 w-4" />
                            )}
                          </Button>
                        </div>
                      </div>
                    ))}

                    <p className="text-xs text-muted-foreground mt-4">
                      Tu pedido será procesado una vez confirmada la transferencia (24-48 hrs hábiles)
                    </p>
                    <div className="space-y-2 mt-2">
                      <Label htmlFor="spei-reference" className="text-sm font-medium">
                        Número de referencia de tu transferencia *
                      </Label>
                      <Input
                        id="spei-reference"
                        placeholder="Ej: 123456789012"
                        value={speiReference}
                        onChange={(e) => setSpeiReference(e.target.value)}
                        className="font-mono"
                      />
                      <p className="text-xs text-muted-foreground">
                        Ingresa el folio o referencia de tu transferencia SPEI para confirmar tu pedido.
                      </p>
                    </div>
                  </div>
                )}

                {/* Payment Buttons */}
                {paymentMethod === 'mercadopago' ? (
                  <Button
                    onClick={handleMercadoPagoPayment}
                    disabled={isProcessing}
                    className="w-full py-6 text-lg bg-[#009ee3] hover:bg-[#008ed0]"
                  >
                    {isProcessing ? (
                      <Loader2 className="animate-spin mr-2" size={20} />
                    ) : (
                      <CreditCard className="mr-2" size={20} />
                    )}
                    Pagar con MercadoPago
                  </Button>
                ) : (
                  <Button
                    onClick={handleConfirmSPEI}
                    disabled={isProcessing || !speiReference.trim()}
                    className="w-full py-6 text-lg btn-gold"
                  >
                    {isProcessing ? (
                      <Loader2 className="animate-spin mr-2" size={20} />
                    ) : (
                      <CheckCircle2 className="mr-2" size={20} />
                    )}
                    Ya realicé la transferencia
                  </Button>
                )}
              </CardContent>
            </Card>
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default CheckoutContraoferta;
