import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { z } from 'zod';
import { 
  Phone, 
  Mail, 
  Clock, 
  Send,
  MessageCircle,
  ArrowRight,
  Loader2,
  CheckCircle
} from 'lucide-react';

const contactSchema = z.object({
  name: z.string().trim().min(2, 'El nombre debe tener al menos 2 caracteres').max(100),
  email: z.string().trim().email('Correo electrónico inválido').max(255),
  phone: z.string().trim().max(20).optional(),
  company: z.string().trim().max(100).optional(),
  subject: z.string().trim().min(5, 'El asunto debe tener al menos 5 caracteres').max(200),
  message: z.string().trim().min(10, 'El mensaje debe tener al menos 10 caracteres').max(2000),
});

const contactInfo = [
  {
    icon: Phone,
    title: 'Teléfono México',
    value: '662-168-0047',
    href: 'tel:662-168-0047',
  },
  {
    icon: Phone,
    title: 'Teléfono USA',
    value: '956-321-8438',
    href: 'tel:956-321-8438',
  },
  {
    icon: Mail,
    title: 'Correo México',
    value: 'ventas@mercadoindustrial.mx',
    href: 'mailto:ventas@mercadoindustrial.mx',
  },
  {
    icon: Mail,
    title: 'Correo USA',
    value: 'industrialmarketllc@gmail.com',
    href: 'mailto:industrialmarketllc@gmail.com',
  },
];

const Contacto = () => {
  const { toast } = useToast();
  const { user, profile } = useAuth();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [formData, setFormData] = useState({
    name: profile?.full_name || '',
    email: profile?.email || '',
    phone: profile?.phone || '',
    company: '',
    subject: '',
    message: '',
  });
  const [errors, setErrors] = useState<Record<string, string>>({});

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { id, value } = e.target;
    setFormData(prev => ({ ...prev, [id]: value }));
    if (errors[id]) {
      setErrors(prev => ({ ...prev, [id]: '' }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrors({});

    // Validate
    const result = contactSchema.safeParse(formData);
    if (!result.success) {
      const fieldErrors: Record<string, string> = {};
      result.error.errors.forEach(err => {
        if (err.path[0]) {
          fieldErrors[err.path[0] as string] = err.message;
        }
      });
      setErrors(fieldErrors);
      return;
    }

    setIsSubmitting(true);

    try {
      const { error } = await supabase
        .from('support_tickets')
        .insert({
          name: formData.name,
          email: formData.email,
          phone: formData.phone || null,
          company: formData.company || null,
          subject: formData.subject,
          message: formData.message,
          user_id: user?.id || null,
          ticket_number: '', // Will be auto-generated by trigger
        });

      if (error) throw error;

      setSubmitted(true);
      toast({
        title: '¡Mensaje enviado!',
        description: 'Te responderemos a la brevedad. Gracias por contactarnos.',
      });
    } catch (error) {
      console.error('Error submitting contact form:', error);
      toast({
        title: 'Error',
        description: 'No se pudo enviar tu mensaje. Intenta de nuevo.',
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />
      
      <main className="flex-1">
        {/* Hero Section */}
        <section className="bg-secondary py-16 md:py-24">
          <div className="container mx-auto px-4">
            <div className="max-w-3xl mx-auto text-center">
              <div className="inline-flex items-center justify-center w-16 h-16 bg-primary/10 rounded-2xl mb-6">
                <MessageCircle className="w-8 h-8 text-primary" />
              </div>
              <h1 className="text-3xl md:text-4xl lg:text-5xl font-display font-bold text-secondary-foreground mb-4">
                Contáctanos
              </h1>
              <p className="text-lg text-secondary-foreground/70">
                Estamos aquí para ayudarte. Escríbenos o llámanos y te responderemos a la brevedad.
              </p>
            </div>
          </div>
        </section>

        {/* Contact Section */}
        <section className="py-16 md:py-24">
          <div className="container mx-auto px-4">
            <div className="grid lg:grid-cols-2 gap-12 max-w-6xl mx-auto">
              {/* Contact Form */}
              <Card>
                <CardContent className="p-8">
                  {submitted ? (
                    <div className="text-center py-12">
                      <div className="w-16 h-16 bg-green-500/10 rounded-full flex items-center justify-center mx-auto mb-4">
                        <CheckCircle className="w-8 h-8 text-green-500" />
                      </div>
                      <h2 className="text-2xl font-display font-bold text-foreground mb-2">
                        ¡Mensaje enviado!
                      </h2>
                      <p className="text-muted-foreground mb-6">
                        Hemos recibido tu mensaje y te responderemos a la brevedad.
                      </p>
                      <Button onClick={() => {
                        setSubmitted(false);
                        setFormData({ name: '', email: '', phone: '', company: '', subject: '', message: '' });
                      }}>
                        Enviar otro mensaje
                      </Button>
                    </div>
                  ) : (
                    <>
                      <h2 className="text-2xl font-display font-bold text-foreground mb-6">
                        Envíanos un mensaje
                      </h2>
                      <form className="space-y-6" onSubmit={handleSubmit}>
                        <div className="grid sm:grid-cols-2 gap-4">
                          <div className="space-y-2">
                            <Label htmlFor="name">Nombre completo *</Label>
                            <Input 
                              id="name" 
                              placeholder="Tu nombre" 
                              value={formData.name}
                              onChange={handleChange}
                              className={errors.name ? 'border-destructive' : ''}
                            />
                            {errors.name && <p className="text-sm text-destructive">{errors.name}</p>}
                          </div>
                          <div className="space-y-2">
                            <Label htmlFor="company">Empresa</Label>
                            <Input 
                              id="company" 
                              placeholder="Nombre de tu empresa" 
                              value={formData.company}
                              onChange={handleChange}
                            />
                          </div>
                        </div>
                        <div className="grid sm:grid-cols-2 gap-4">
                          <div className="space-y-2">
                            <Label htmlFor="email">Correo electrónico *</Label>
                            <Input 
                              id="email" 
                              type="email" 
                              placeholder="tu@email.com" 
                              value={formData.email}
                              onChange={handleChange}
                              className={errors.email ? 'border-destructive' : ''}
                            />
                            {errors.email && <p className="text-sm text-destructive">{errors.email}</p>}
                          </div>
                          <div className="space-y-2">
                            <Label htmlFor="phone">Teléfono</Label>
                            <Input 
                              id="phone" 
                              type="tel" 
                              placeholder="+52 662 123 4567" 
                              value={formData.phone}
                              onChange={handleChange}
                            />
                          </div>
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="subject">Asunto *</Label>
                          <Input 
                            id="subject" 
                            placeholder="¿En qué podemos ayudarte?" 
                            value={formData.subject}
                            onChange={handleChange}
                            className={errors.subject ? 'border-destructive' : ''}
                          />
                          {errors.subject && <p className="text-sm text-destructive">{errors.subject}</p>}
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="message">Mensaje *</Label>
                          <Textarea 
                            id="message" 
                            placeholder="Escribe tu mensaje aquí..." 
                            rows={5}
                            value={formData.message}
                            onChange={handleChange}
                            className={errors.message ? 'border-destructive' : ''}
                          />
                          {errors.message && <p className="text-sm text-destructive">{errors.message}</p>}
                        </div>
                        <Button className="w-full btn-gold" size="lg" disabled={isSubmitting}>
                          {isSubmitting ? (
                            <>
                              <Loader2 size={18} className="mr-2 animate-spin" />
                              Enviando...
                            </>
                          ) : (
                            <>
                              <Send size={18} className="mr-2" />
                              Enviar mensaje
                            </>
                          )}
                        </Button>
                      </form>
                    </>
                  )}
                </CardContent>
              </Card>

              {/* Contact Info */}
              <div className="space-y-6">
                <h2 className="text-2xl font-display font-bold text-foreground mb-6">
                  Información de contacto
                </h2>
                
                <div className="grid sm:grid-cols-2 gap-4">
                  {contactInfo.map((item, index) => (
                    <a
                      key={index}
                      href={item.href}
                      className="flex items-start gap-4 p-4 bg-card rounded-xl hover:shadow-lg transition-shadow"
                    >
                      <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center shrink-0">
                        <item.icon className="w-5 h-5 text-primary" />
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground">{item.title}</p>
                        <p className="font-semibold text-foreground">{item.value}</p>
                      </div>
                    </a>
                  ))}
                </div>

                {/* Hours */}
                <div className="p-6 bg-card rounded-xl">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center">
                      <Clock className="w-5 h-5 text-primary" />
                    </div>
                    <h3 className="font-semibold text-foreground">Horario de atención</h3>
                  </div>
                  <div className="space-y-2 text-muted-foreground">
                    <p>Lunes a Viernes: 8:00 AM - 6:00 PM</p>
                    <p>Sábados: 8:00 AM - 1:00 PM</p>
                    <p>Domingos: Cerrado</p>
                  </div>
                </div>

                {/* WhatsApp CTA */}
                <a
                  href="https://wa.me/526621680047"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center justify-center gap-3 w-full p-4 bg-green-500 hover:bg-green-600 text-white rounded-xl font-semibold transition-colors"
                >
                  <MessageCircle size={24} />
                  Chatea con nosotros por WhatsApp
                </a>
              </div>
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-12 bg-muted/50">
          <div className="container mx-auto px-4 text-center">
            <p className="text-muted-foreground mb-4">
              ¿Prefieres explorar nuestros productos primero?
            </p>
            <Button asChild variant="outline" size="lg" className="gap-2">
              <Link to="/catalogo">
                Ver catálogo
                <ArrowRight size={18} />
              </Link>
            </Button>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default Contacto;
